import os
import sys
import spacy
import argparse
import collections
import logging

import numpy as np

parser = argparse.ArgumentParser(
    description="Generates a new set of vectors corresponding to a "
                "vocabulary and dumps it into a file called `w2v.npy`."
                " For any give word, if the word appears among spaCy's"
                " vectors, then the spaCy's vector corresponding to it"
                " is used. Otherwise, a randomly initialized vector is"
                " used.")
parser.add_argument(
    "infile",
    nargs="?",
    type=argparse.FileType("r"),
    default=sys.stdin,
    help="A vocabulary file (e.g., `vocab.txt` generated by "
         "generate_vocabulary.py).")

args = parser.parse_args()
spacy_nlp = spacy.load('de')
spacy_tokenizer = spacy_nlp.tokenizer

vocab_tokens = []
for line in args.infile:
  vocab_tokens.append(line.strip().split('\t')[0])

w2v = np.random.rand(len(vocab_tokens) , 300)

for t_i, term in enumerate(vocab_tokens):
  if spacy_nlp(term).has_vector:
    w2v[t_i] = spacy_nlp(term).vector

print('Vocab_Size: {}\nW2V Shape: {}'.format(len(vocab_tokens), w2v.shape))
np.save('w2v.npy', w2v)
